IdentityServerSample.IdentityServer.AdminPanel/Models/ClaimViewModel.cs
namespace IdentityServerSample.IdentityServer.AdminPanel.Models
{
    public class ClaimViewModel
    {
        public int Id { get; set; }

        public string Type { get; set; }

        public string Value { get; set; }

        public ClaimViewModel(int id, string type, string value)
        {
            Id = id;
            Type = type;
            Value = value;
        }
    }
}

IdentityServerSample.IdentityServer.AdminPanel/Models/ErrorViewModel.cs
using System;

namespace IdentityServerSample.IdentityServer.AdminPanel.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IdentityServerSample.IdentityServer.AdminPanel/Models/IdentityAppViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IdentityServerSample.IdentityServer.AdminPanel.Models
{
    public class IdentityAppViewModel
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public string DisplayName { get; set; }

        public string Type { get; set; }

        public IdentityAppViewModel(string id, string name, string displayName, string type)
        {
            Id = id;
            Name = name;
            DisplayName = displayName;
            Type = type;
        }
    }
}

IdentityServerSample.IdentityServer.AdminPanel/Models/UserEditViewModel.cs
using System.Collections.Generic;
using IdentityServerSample.IdentityServer.AdminPanel.Binders;
using Microsoft.AspNetCore.Mvc;

namespace IdentityServerSample.IdentityServer.AdminPanel.Models
{
    [ModelBinder(BinderType = typeof(UserEditViewModelBinder))]
    public class UserEditViewModel
    {
        public string Id { get; set; }

        public string UserName { get; set; }

        public List<ClaimViewModel> Claims { get; set; }

        public int ClaimAmount { get; set; }
    }
}

IdentityServerSample.IdentityServer.AdminPanel/Controllers/AccountController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IdentityServerSample.IdentityServer.AdminPanel.Controllers
{
    [AllowAnonymous]
    public class AccountController : Controller
    {

        public async Task Logout()
        {
            await HttpContext.SignOutAsync("Cookies");
            await HttpContext.SignOutAsync("oidc");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

    }
}

IdentityServerSample.IdentityServer.AdminPanel/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using IdentityServerSample.IdentityServer.AdminPanel.Models;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using IdentityServer4.EntityFramework.DbContexts;
using System.Linq;

namespace IdentityServerSample.IdentityServer.AdminPanel.Controllers
{
    public class HomeController : Controller
    {
        readonly ConfigurationDbContext _configCtx;

        public HomeController(ConfigurationDbContext configCtx)
        {
            _configCtx = configCtx;
        }

        public async Task<IActionResult> Index()
        {
            var a = User;

            string accessToken = await HttpContext.GetTokenAsync("access_token");
            string idToken = await HttpContext.GetTokenAsync("id_token");

            var b = _configCtx.Clients.ToList();

            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IdentityServerSample.IdentityServer.AdminPanel/Controllers/IdentityAppsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IdentityServer4.EntityFramework.DbContexts;
using IdentityServerSample.IdentityServer.AdminPanel.Models;
using IdentityServerSample.Shared.Constants;
using Microsoft.AspNetCore.Mvc;

namespace IdentityServerSample.IdentityServer.AdminPanel.Controllers
{
    public class IdentityAppsController : Controller
    {
        readonly ConfigurationDbContext _configCtx;

        public IdentityAppsController(ConfigurationDbContext configCtx)
        {
            _configCtx = configCtx;
        }

        public IActionResult Index()
        {
            var model = new List<IdentityAppViewModel>();
            model.AddRange(_configCtx.ApiResources.Select(x => new IdentityAppViewModel(x.Id.ToString(), x.Name, x.DisplayName, ISAppTypes.ApiResource)));
            model.AddRange(_configCtx.Clients.Select(x => new IdentityAppViewModel(x.Id.ToString(), x.ClientId, x.ClientName, ISAppTypes.Client)));
            return View(model);
        }
    }
}

IdentityServerSample.IdentityServer.AdminPanel/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using IdentityServerSample.IdentityServer.AdminPanel.Business;
using IdentityServerSample.IdentityServer.AdminPanel.Data.Dtos;
using IdentityServerSample.IdentityServer.AdminPanel.Models;
using Microsoft.AspNetCore.Mvc;

namespace IdentityServerSample.IdentityServer.AdminPanel.Controllers
{
    public class UsersController : Controller
    {
        readonly IUsersLogic _usersLogic;

        public UsersController(IUsersLogic usersLogic)
        {
            _usersLogic = usersLogic;
        }

        public IActionResult Index()
        {
            return View(_usersLogic.GetAll());
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            var user = _usersLogic.Get(id);
            var model = new UserEditViewModel();
            model.Id = user.Id;
            model.UserName = user.UserName;
            model.Claims = user.Claims.Select(x => new ClaimViewModel(x.Key, x.Value.Type, x.Value.Value)).ToList();
            model.ClaimAmount = user.Claims.Count;
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(UserEditViewModel model)
        {
            var user = new UserDto();
            user.Id = model.Id;
            user.UserName = model.UserName;
            user.Claims = model.Claims.Select(x => new KeyValuePair<int, Claim>(x.Id, new Claim(x.Type, x.Value))).ToDictionary(x => x.Key, y => y.Value);
            _usersLogic.Update(user);
            return Redirect("~/Users/");
        }
    }
}

IdentityServerSample.IdentityServer.AdminPanel/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

IdentityServerSample.IdentityServer.AdminPanel/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

IdentityServerSample.IdentityServer.AdminPanel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

IdentityServerSample.IdentityServer.AdminPanel/Views/IdentityApps/Index.cshtml
@model List<IdentityServerSample.IdentityServer.AdminPanel.Models.IdentityAppViewModel>

@{
    ViewData["Title"] = "Identity Server Applications";
}

<h2>Identity Server Applications</h2>

<ul class="list-group">
    @foreach (var app in Model)
    {
        <li class="list-group-item container">
            <span class="col-sm-1">@app.Id</span>
            <span class="col-sm-5">@app.DisplayName</span>
            <span class="col-sm-3">@app.Name</span>
            <span class="col-sm-3">@app.Type</span>
        </li>
    }
</ul>

IdentityServerSample.IdentityServer.AdminPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityServerSample.IdentityServer.AdminPanel</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">IdentityServerSample.IdentityServer.AdminPanel</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                    <li><a asp-area="" asp-controller="IdentityApps" asp-action="Index">Apps</a></li>
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - IdentityServerSample.IdentityServer.AdminPanel</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

IdentityServerSample.IdentityServer.AdminPanel/Views/Users/Edit.cshtml
@model IdentityServerSample.IdentityServer.AdminPanel.Models.UserEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-sm-5">
                    <div class="form-group">
                        <label asp-for="Id" class="control-label"></label>
                        <input asp-for="Id" class="form-control" disabled />
                        <span asp-validation-for="Id" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="UserName" class="control-label"></label>
                        <input asp-for="UserName" class="form-control" />
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>

                </div>

                <div class="col-sm-2"></div>

                <div class="col-sm-5">
                    <div class="vdivide-left"></div>
                    <div class="form-group">
                        <label asp-for="Claims" class="control-label"></label>
                        <input type="hidden" asp-for="@Model.ClaimAmount" class="form-control" value="@Model.ClaimAmount" />
                        <br />
                        @for (int i = 0; i < Model.Claims.Count(); i++)
                        {
                            <input type="hidden" asp-for="@Model.Claims[i].Id" class="form-control" value="@Model.Claims[i].Id" />
                            <label class="control-label">@Model.Claims[i].Type</label>
                            <input type="hidden" asp-for="@Model.Claims[i].Type" class="form-control" value="@Model.Claims[i].Type" />
                            <input asp-for="@Model.Claims[i].Value" class="form-control" value="@Model.Claims[i].Value" />
                        }
                    </div>

                    <div class="form-group pull-right">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>

            </div>


        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

IdentityServerSample.IdentityServer.AdminPanel/Views/Users/Index.cshtml
@model List<IdentityServerSample.IdentityServer.AdminPanel.Data.Dtos.UserDto>

@{
    ViewData["Title"] = "Users";
}

<h2>Users</h2>

<ul class="list-group">
    @foreach (var user in Model)
    {
        <li class="list-group-item container">
            <span class="pull-left">@user.Id - @user.UserName</span>
            <a asp-action="Edit" asp-controller="Users" asp-route-id="@user.Id" class="btn btn-default pull-right">Edit</a>
        </li>
    }
</ul>